#!/usr/bin/env bash

if [ "$(basename $PWD)" != '_bin' ]; then
  printf "$(tput setaf 1)[ERROR]$(tput sgr0)Must be executed from the _bin directory\n" 1>&2
  exit 1
fi

git show origin/master:README.md > ../index.md
sed '1  i\
---\
layout: default\
title: Linux Tips\
---\
' ../index.md > tmpfile

mv tmpfile ../index.md

printf "$(tput setaf 2) Updated index! $(tput sgr0)\n";